[project]
name = "flash-core"
version = "0.1.2-alpha.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "YeLinAung", email = "40236753+b14cknc0d3@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.0",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.12.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
pythonpath = ["src"]
addopts = "--cov=flash_core"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
