[project]
name = "flash-web-framework"
version = "0.0.0"
description = "Python monorepo"
requires-python = ">=3.12"

[tool.uv]
workspace = { members = ["packages/*"] }


[tool.pytest.ini_options]
asyncio_mode = "strict"
