[project]
name = "flash-admin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "YeLinAung", email = "40236753+b14cknc0d3@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "flash_db"
]
[tool.uv.sources]
flash-db = { workspace = true}

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

