[project]
name = "flash-db"
version = "0.3.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "YeLinAung", email = "40236753+b14cknc0d3@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "sqlalchemy[asyncio]>=2.0.45",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "aiosqlite>=0.22.1",
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "pytest-cov>=7.0.0",
]
