[project]
name = "flash-authentication"
version = "0.1.1-alpha.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "YeLinAung", email = "40236753+b14cknc0d3@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "flash_db",
    "pydantic[email]>=2.12.5",
]

[tool.uv.sources]
flash-db = { workspace = true}

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
